### ISSUE TITLE
Indexing exception

### ISSUE THREAD

**Issue by alex-coder** [spectacles/CodeComplice#15]
On update index i got follow exception:

```
Exception! /var/www/gui/public/js/services/UsersService.js:328 (JavaScript)
Traceback (most recent call last):
  File "/home/alex/.config/sublime-text-3/Packages/CodeComplice/CodeComplice.py", line 906, in get_trg
    trg = getattr(buf, type, lambda *a: None)(*args, **kwargs)
  File "/home/alex/.config/sublime-text-3/Packages/CodeComplice/libs/codeintel2/buffer.py", line 208, in preceding_trg_from_pos
    return self.langintel.preceding_trg_from_pos(self, pos, curr_pos, trigger_type=trigger_type)
  File "/home/alex/.config/sublime-text-3/Packages/CodeComplice/libs/codeintel2/lang_javascript.py", line 580, in preceding_trg_from_pos
    DEBUG=DEBUG)
  File "/home/alex/.config/sublime-text-3/Packages/CodeComplice/libs/codeintel2/langintel.py", line 492, in preceding_trg_from_pos
    trg = buf.trg_from_pos(p, implicit=False, trigger_type=trigger_type)
  File "/home/alex/.config/sublime-text-3/Packages/CodeComplice/libs/codeintel2/buffer.py", line 175, in trg_from_pos
    return self.langintel.trg_from_pos(self, pos, implicit, type=trigger_type)
TypeError: trg_from_pos() got an unexpected keyword argument 'type'
+ Info: Error indexing! Please send the log file: '/home/alex/.codeintel/codeintel.log
```

this happens not only with JS, with PHP i have same problem

**Comment by spectacles** [comment]
I fixed this and re-released v1.0.6! So if you remove CodeComplice and reinstall from packagecontrol, it will be working. Thanx for your help!

**Comment by alex-coder** [comment]
Seems to be working. 
Thanx!

**Comment by spectacles** [comment]
I'll reopen the issue until v1.0.7 has been released, so people can find the fix!
