### ISSUE TITLE
ST3 build 3088 update

### ISSUE THREAD

**Issue by 72CZR** [spectacles/CodeComplice#37]
There seems to be a problem with CodeComplice on ST3 build 3088,
I'm getting lots of: (on startup)
```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 272, in on_modified
    callback.on_modified(v)
  File "C:\Users\CZR\AppData\Roaming\Sublime Text 3\Packages\CodeComplice\CodeComplice.py", line 1516, in on_modified
    sublime_scope = getSublimeScope(view)
  File "C:\Users\CZR\AppData\Roaming\Sublime Text 3\Packages\CodeComplice\CodeComplice.py", line 416, in getSublimeScope
    return view.scope_name(pos)
  File "C:\Program Files\Sublime Text 3\sublime.py", line 737, in scope_name
    return sublime_api.view_scope_name(self.view_id, pt)
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 18-19: invalid continuation byte
```

Tried to do some digging, turns out it could be a bad encoded .py file ? Of course I checked some, but all seem encoded UTF-8 (which is ok)

Win 8.1 x64, ST 3 3088, CodeComplice 1.1.3 (installed from GIT, not package manager).
Everything was fine untill the recent ST update.

Current status:
- Autocomplete still works with proper function definition BUT, code_intel_auto_complete command stopped working, giving errors like:
```
+ Warning: evaluating 'numberFormat' at ajax_form.php#8: could not resolve first part of 'numberFormat'
evaluating 'numberFormat' at ajax_form.php#8: could not resolve first part of 'numberFormat'
```
(tested custom function numberFormat() for above example)

**Comment by 72CZR** [comment]
Seems that it works on my 2nd installation (same OS, same plugins, same ST version). Only difference is that I installed CodeComplice via Package Manager, will try reinstall and get back with info

**Comment by spectacles** [comment]
so package manager was working for you? thanx for reporting!

**Comment by 72CZR** [comment]
No no, what I ment was, it's working on my 2nd computer (which has the same plugins/sublime version/os etc).
Package manager is working fine on both.

Reinstalled using package manager, still no luck.
Switched project and wow, it works !

Seems there's an encoding problem with my first project maybe ?

While indexing, I saw this:
```
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 18-19: invalid continuation byte
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 272, in on_modified
    callback.on_modified(v)
  File "C:\Users\CZR\AppData\Roaming\Sublime Text 3\Packages\CodeComplice\CodeComplice.py", line 1516, in on_modified
    sublime_scope = getSublimeScope(view)
  File "C:\Users\CZR\AppData\Roaming\Sublime Text 3\Packages\CodeComplice\CodeComplice.py", line 416, in getSublimeScope
    return view.scope_name(pos)
  File "C:\Program Files\Sublime Text 3\sublime.py", line 737, in scope_name
    return sublime_api.view_scope_name(self.view_id, pt)
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 18-19: invalid continuation byte
```
But ST says all files are UTF-8. Ideas ?

**Comment by 666CZR** [comment]
Tried your last commit :) Autocomplete popup works on demand on the project it didn't work before.
However,

```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 272, in on_modified
    callback.on_modified(v)
  File "C:\Users\CZR\AppData\Roaming\Sublime Text 3\Packages\CodeComplice\CodeComplice.py", line 1524, in on_modified
    lang = guess_lang(view, path, sublime_scope)
  File "C:\Users\CZR\AppData\Roaming\Sublime Text 3\Packages\CodeComplice\CodeComplice.py", line 462, in guess_lang
    syntax = os.path.splitext(os.path.basename(view.settings().get('syntax')))[0]
  File "./ntpath.py", line 309, in basename
  File "./ntpath.py", line 280, in split
  File "./ntpath.py", line 208, in splitdrive
TypeError: object of type 'NoneType' has no len()
```
