### ISSUE TITLE
[Bug] Go Definition

### ISSUE THREAD

**Issue by ptcong** [spectacles/CodeComplice#9]
I don't remember when the issue starts occured, but today i try to use GoTo Definition of CodeCompilce to go to a method in current class, but it does not work.

This is error log:
```
Exception in thread scanning thread:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "./threading.py", line 858, in run
  File "/Users/ptcong/Library/Application Support/Sublime Text 3/Packages/CodeComplice/CodeComplice.py", line 869, in _codeintel_scan
    buf.scan(mtime=mtime, skip_scan_time_check=is_dirty)
UnboundLocalError: local variable 'mtime' referenced before assignment
```
I just check the CodeComplice.py, and it seem does not define `mtime` variable if `is_dirty = false`

**Comment by spectacles** [comment]
It will be working in next release, thanx!
